import {platformsLogos} from "../variables";

[
  { "name": "Cryptocurrency", "link": "https://www.linkedin.com/groups/3135803/", "logo": platformsLogos + 'b141.webp', "SN": 1 },
  { "name": "Blockchain & Cryptocurrency", "link": "https://www.linkedin.com/groups/7008772/", "logo": platformsLogos + 'b196.webp', "SN": 2 },
  { "name": "Cryptocurrency Investors", "link": "https://www.linkedin.com/groups/8802491/", "logo": platformsLogos + 'b220.webp', "SN": 3 },
  { "name": "Cryptocurrency News", "link": "https://www.linkedin.com/groups/11588727/", "logo": platformsLogos + 'b122.webp', "SN": 4 },
  { "name": "Blockchain and Cryptocurrency Enthusiasts", "link": "https://www.linkedin.com/groups/7099231/", "logo": platformsLogos + 'b25.webp', "SN": 5 },
  { "name": "Crypto and Blockchain Professionals", "link": "https://www.linkedin.com/groups/6843489/", "logo": platformsLogos + 'b142.webp', "SN": 6 },
  { "name": "Bitcoin & Cryptocurrency Technology", "link": "https://www.linkedin.com/groups/18502358/", "logo": platformsLogos + 'b143.webp', "SN": 7 },
  { "name": "CryptoCurrency Trading", "link": "https://www.linkedin.com/groups/10137884/", "logo": platformsLogos + 'b17.webp', "SN": 8 },
  { "name": "Blockchain, Crypto & Digital Assets", "link": "https://www.linkedin.com/groups/10756891/", "logo": platformsLogos + 'b129.webp', "SN": 9 },
  { "name": "Bitcoin & Cryptocurrency Investors", "link": "https://www.linkedin.com/groups/12183046/", "logo": platformsLogos + 'b143.webp', "SN": 10 },
  { "name": "Blockchain & Cryptocurrency Education", "link": "https://www.linkedin.com/groups/10876394/", "logo": platformsLogos + 'b118.webp', "SN": 11 },
  { "name": "Ethereum & Cryptocurrency", "link": "https://www.linkedin.com/groups/12758372/", "logo": platformsLogos + 'b175.webp', "SN": 12 },
  { "name": "CryptoCurrency & Blockchain Network", "link": "https://www.linkedin.com/groups/3021467/", "logo": platformsLogos + 'b163.webp', "SN": 13 },
  { "name": "Crypto Investment & Blockchain", "link": "https://www.linkedin.com/groups/5324856/", "logo": platformsLogos + 'b65.webp', "SN": 14 },
  { "name": "Blockchain for Crypto & Finance", "link": "https://www.linkedin.com/groups/9089350/", "logo": platformsLogos + 'b100.webp', "SN": 15 },
  { "name": "Cryptocurrency Entrepreneurs & Investors", "link": "https://www.linkedin.com/groups/11017245/", "logo": platformsLogos + 'b14.webp', "SN": 16 },
  { "name": "Cryptocurrency Technology & Innovation", "link": "https://www.linkedin.com/groups/9126041/", "logo": platformsLogos + 'b37.webp', "SN": 17 },
  { "name": "Bitcoin & Blockchain Professionals", "link": "https://www.linkedin.com/groups/9132712/", "logo": platformsLogos + 'b173.webp', "SN": 18 },
  { "name": "Crypto & Blockchain Discussions", "link": "https://www.linkedin.com/groups/7813324/", "logo": platformsLogos + 'b105.webp', "SN": 19 },
  { "name": "Blockchain and Crypto Technology", "link": "https://www.linkedin.com/groups/10773428/", "logo": platformsLogos + 'b67.webp', "SN": 20 },
  { "name": "Cryptocurrency & ICOs", "link": "https://www.linkedin.com/groups/6430220/", "logo": platformsLogos + 'b103.webp', "SN": 21 },
  { "name": "Blockchain for Crypto Traders", "link": "https://www.linkedin.com/groups/4673789/", "logo": platformsLogos + 'b167.webp', "SN": 22 },
  { "name": "Crypto and Blockchain Startups", "link": "https://www.linkedin.com/groups/7029087/", "logo": platformsLogos + 'b213.webp', "SN": 23 },
  { "name": "Cryptocurrency for Business", "link": "https://www.linkedin.com/groups/11653699/", "logo": platformsLogos + 'b2.webp', "SN": 24 },
  { "name": "Cryptocurrency Market Insights", "link": "https://www.linkedin.com/groups/5236743/", "logo": platformsLogos + 'b45.webp', "SN": 25 },
  { "name": "Blockchain, Cryptocurrency & ICO Community", "link": "https://www.linkedin.com/groups/13467787/", "logo": platformsLogos + 'b16.webp', "SN": 26 },
  { "name": "Crypto Trading & Investment", "link": "https://www.linkedin.com/groups/13759789/", "logo": platformsLogos + 'b180.webp', "SN": 27 },
  { "name": "Crypto Investment & Blockchain Network", "link": "https://www.linkedin.com/groups/2094729/", "logo": platformsLogos + 'b9.webp', "SN": 28 },
  { "name": "Blockchain, Bitcoin & Cryptocurrency Network", "link": "https://www.linkedin.com/groups/5896037/", "logo": platformsLogos + 'b12.webp', "SN": 29 },
  { "name": "Crypto and Blockchain Business", "link": "https://www.linkedin.com/groups/11703272/", "logo": platformsLogos + 'b109.webp', "SN": 30 }
]
